(()=>{
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const plans=[
{id:'free',name:'免費版',short:'免費',best:'基本問答、檔案分析與輕量使用'},
{id:'plus',name:'Google AI Plus',short:'Plus',best:'一般個人生產力、內容與較高額度'},
{id:'pro',name:'Google AI Pro',short:'Pro',best:'高頻研究、長文件、開發與 Gemini Spark'},
{id:'ultra',name:'Google AI Ultra',short:'Ultra',best:'最高推理與生成額度、Deep Think'}];
const features=[
['模型與用量','Gemini App','標準額度','較高額度','高額度','最高額度','方案主要差異在額度與優先權，不是模型名稱。'],
['模型與用量','脈絡窗口','32K','128K','1M','1M','長文件與大型專案優先考量 Pro 以上。'],
['研究與知識','Deep Research','有限','較高','更高','最高','正式報告仍需檢查來源、日期與推論。'],
['研究與知識','Gemini Notebook','基本額度','較高額度','高額度','最高額度','適合來源導向研究、備課與長期專案。'],
['代理自動化','Scheduled Actions','分批開放','包含','包含','包含','實際資格受帳號、地區與推出狀態影響。'],
['代理自動化','Gemini Spark','—','—','包含','包含','個人雲端代理；企業資料不可直接以私人帳號取代治理平台。'],
['內容生成','Canvas／Gems','基本','包含','包含','包含','建立成果與固定專家助理。'],
['內容生成','圖像與影片','有限','較高','高','最高','生成媒體仍需檢查肖像、品牌與著作權。'],
['Workspace','Gmail 內 Gemini','有限／依帳號','包含','較完整','較完整','公司帳號功能應看 Workspace 授權。'],
['Workspace','Docs／Sheets／Slides／Vids','依帳號','部分','較完整','較完整','個人方案不能替代組織版權限、DLP 與稽核。'],
['開發工具','AI Studio／Antigravity／Jules','基本','較高','高','最高','正式 API 與 Cloud 資源仍可能獨立計費。'],
['其他','儲存空間','帳號既有容量','方案容量','較大容量','最大容量','容量與價格依臺灣官方頁面及促銷狀態。']];
const usecases=[
{id:'pmo',cat:'knowledge',title:'PMO／專案管理',primary:'Workspace + Notebook',fallback:'Gemini App + Docs',risk:'會議結論與責任歸屬需人工確認',auto:'中',desc:'需求彙整、會議摘要、風險清單、週報與決策紀錄。'},
{id:'training',cat:'content',title:'企業培訓與備課',primary:'Notebook + Canvas + Slides',fallback:'Gemini App + Docs',risk:'答案、難度與版權需審稿',auto:'中',desc:'教材分析、教案、簡報、題庫與差異化解說。'},
{id:'research',cat:'knowledge',title:'研究與情報蒐集',primary:'Deep Research + Notebook',fallback:'AI Mode + Sheets',risk:'來源權威性與日期',auto:'中',desc:'市場研究、競品、政策與技術趨勢整理。'},
{id:'workflow',cat:'automation',title:'工作流自動化',primary:'Workspace Studio／Spark',fallback:'Apps Script',risk:'誤寄、誤刪與提示注入',auto:'高',desc:'信件分類、附件擷取、排程彙整與狀態通知。'},
{id:'data',cat:'general',title:'資料分析與報表',primary:'Sheets + BigQuery + Looker',fallback:'Gemini App + CSV',risk:'指標定義與資料品質',auto:'中高',desc:'公式、資料清理、KPI、圖表與異常診斷。'},
{id:'marketing',cat:'content',title:'行銷與多媒體',primary:'Canvas + Nano Banana + Vids',fallback:'Gemini App',risk:'品牌一致性與權利',auto:'中',desc:'文案、圖片、影片腳本與素材變體。'},
{id:'dev',cat:'technical',title:'軟體開發',primary:'AI Studio + Gemini API',fallback:'Gemini App',risk:'安全、測試與授權',auto:'高',desc:'原型、結構化輸出、函式呼叫、測試與除錯。'},
{id:'search',cat:'business',title:'企業知識搜尋',primary:'Gemini Enterprise + Agent Search',fallback:'Notebook',risk:'權限錯配與過期文件',auto:'中高',desc:'企業 RAG、權限感知搜尋與內部服務台。'},
{id:'cx',cat:'business',title:'客服與顧客體驗',primary:'Gemini Enterprise CX',fallback:'API 客服原型',risk:'錯誤承諾與個資',auto:'高',desc:'FAQ、自助服務、客服建議與對話洞察。'},
{id:'security',cat:'technical',title:'雲端與資安',primary:'Cloud Assist + Model Armor',fallback:'人工維運流程',risk:'高權限與誤判',auto:'高',desc:'故障診斷、成本分析、提示注入與資料外洩防護。'}];
const layers=[
['個人 AI','Gemini App、Live、Canvas、Gems、Deep Research、Notebook、Scheduled Actions、Spark。'],
['Google Workspace','Gmail、Docs、Sheets、Slides、Drive、Meet、Chat、Vids 與 Workspace Studio；由組織管理員控管。'],
['開發者平台','Google AI Studio、Gemini API、Function Calling、Structured Output、Live API 與代理工具。'],
['企業代理與搜尋','Gemini Enterprise、Agent Platform、Agent Search、Agent Registry、Model Armor 與 CX。'],
['裝置與實體世界','Gemini in Chrome、Android、Gemini Nano 與 Gemini Robotics；受裝置及地區限制。']];
const modules={
recommend:{title:'主方案',body:s=>recommend(s)},quick:{title:'方案判讀',body:()=>'<b>Plus：</b>一般個人生產力<br><b>Pro：</b>長文件、研究、開發與 Spark<br><b>Ultra：</b>最高強度推理與生成'},
workflow:{title:'導入路徑',body:()=>'<span class="pill">1. 公開資料 PoC</span><span class="pill">2. 人工核准</span><span class="pill">3. 權限與日誌</span><span class="pill">4. 規模化</span>'},
governance:{title:'治理底線',body:s=>s.data==='public'?'<span class="ok">公開或模擬資料可先驗證價值。</span>':'<span class="risk">內部或敏感資料應使用組織帳號、最小權限、日誌與人工核准。</span>'},
metrics:{title:'驗收指標',body:()=>'<b>效率：</b>週期縮短 ≥30%<br><b>品質：</b>關鍵欄位正確率 ≥95%<br><b>安全：</b>未授權外洩與未核准對外動作皆為 0'},
boundary:{title:'產品邊界',body:()=>'<b>個人方案</b>處理個人生產力；<b>Workspace</b>處理組織協作與治理；<b>API／Cloud</b>建立產品；<b>Enterprise</b>處理跨系統代理。'}};
const defaults=['recommend','quick','workflow','governance','metrics','boundary'];
let state={view:'overview',role:'professional',goal:'daily',data:'public',planA:'plus',planB:'pro',group:'all',query:'',app:'all',font:1,editing:false,order:[...defaults]};
try{Object.assign(state,JSON.parse(localStorage.getItem('gemini-live')||'{}'));if(location.hash.startsWith('#s='))Object.assign(state,JSON.parse(decodeURIComponent(escape(atob(location.hash.slice(3))))));}catch{}
state.order=[...new Set([...(Array.isArray(state.order)?state.order:[]),...defaults])].filter(x=>modules[x]);if(!plans.some(x=>x.id===state.planA))state.planA='plus';if(!plans.some(x=>x.id===state.planB)||state.planB===state.planA)state.planB='pro';
const save=()=>{try{localStorage.setItem('gemini-live',JSON.stringify(state))}catch{}document.documentElement.style.setProperty('--font',state.font)};
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function recommend(s){if(s.data==='sensitive')return '<b>Primary：</b>Workspace／Gemini Enterprise<br><b>Fallback：</b>去識別化資料先做 PoC';if(s.goal==='build')return '<b>Primary：</b>AI Studio + Gemini API<br><b>Fallback：</b>Gemini App 原型';if(s.goal==='automation')return s.role==='manager'?'<b>Primary：</b>Workspace Studio／Agent Platform<br><b>Fallback：</b>人工核准流程':'<b>Primary：</b>Google AI Pro + Spark<br><b>Fallback：</b>Scheduled Actions';if(s.goal==='research')return '<b>Primary：</b>Deep Research + Notebook<br><b>Fallback：</b>Gemini App + Drive';if(s.goal==='content')return '<b>Primary：</b>Notebook + Canvas + Slides<br><b>Fallback：</b>Gemini App';return '<b>Primary：</b>Gemini App + Notebook<br><b>Fallback：</b>免費版先驗證使用頻率'}
function profile(){state.role=$('#role').value;state.goal=$('#goal').value;state.data=$('#data').value;$('#profileNote').innerHTML=recommend(state);save();renderDashboard()}
function renderDashboard(){const box=$('#dashboard');box.classList.toggle('editing',state.editing);box.innerHTML=state.order.map((id,i)=>`<article class="module" data-id="${id}"><div class="module-head"><button class="drag" aria-label="拖曳${modules[id].title}">↕</button><h3>${modules[id].title}</h3></div><div class="module-body">${modules[id].body(state)}</div><div class="module-actions"><button data-move="up" ${i===0?'disabled':''}>↑</button><button data-move="down" ${i===state.order.length-1?'disabled':''}>↓</button></div></article>`).join('');dragInit()}
function smart(){const priority=state.data==='sensitive'?['recommend','governance','workflow','boundary','metrics','quick']:state.goal==='automation'?['recommend','workflow','governance','metrics','quick','boundary']:state.goal==='build'?['recommend','boundary','workflow','metrics','governance','quick']:defaults;state.order=[...priority];save();renderDashboard();toast('已依使用情境重新排序')}
function renderPlans(){['planA','planB'].forEach(id=>{$('#'+id).innerHTML=plans.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');$('#'+id).value=state[id]});const groups=['all',...new Set(features.map(x=>x[0]))];$('#planGroup').innerHTML=groups.map(g=>`<option value="${g}">${g==='all'?'全部分類':g}</option>`).join('');$('#planGroup').value=state.group;$('#planSearch').value=state.query;compare()}
function compare(){let q=state.query.trim().toLowerCase(),rows=features.filter(x=>(state.group==='all'||x[0]===state.group)&&(!q||x.join(' ').toLowerCase().includes(q)));if(q&&state.group!=='all'&&!rows.length&&features.some(x=>x.join(' ').toLowerCase().includes(q))){state.group='all';$('#planGroup').value='all';rows=features.filter(x=>x.join(' ').toLowerCase().includes(q));toast('已清除不相容的分類')};const pa=plans.find(x=>x.id===state.planA),pb=plans.find(x=>x.id===state.planB);if(!rows.length){$('#compareResult').innerHTML='<div class="empty"><b>找不到符合條件的功能</b><span>清除搜尋與分類後顯示全部項目。</span><button data-clear="plans">清除篩選</button></div>';return}$('#compareResult').innerHTML=[...new Set(rows.map(x=>x[0]))].map(g=>`<section class="group"><h3>${esc(g)}</h3>${rows.filter(x=>x[0]===g).map(x=>`<article class="feature"><h4>${esc(x[1])}</h4><div class="values"><div class="value"><small>${pa.short}</small><b>${esc(x[2+plans.findIndex(p=>p.id===state.planA)])}</b></div><div class="value"><small>${pb.short}</small><b>${esc(x[2+plans.findIndex(p=>p.id===state.planB)])}</b></div></div><p>${esc(x[6])}</p></article>`).join('')}</section>`).join('')}
function renderApps(){const cats=[['all','全部'],['knowledge','知識工作'],['general','資料分析'],['automation','自動化'],['content','內容／教學'],['technical','技術／開發'],['business','商務／客服']];$('#appFilters').innerHTML=cats.map(x=>`<button data-app="${x[0]}" class="${state.app===x[0]?'active':''}">${x[1]}</button>`).join('');const rows=usecases.filter(x=>state.app==='all'||x.cat===state.app);$('#apps').innerHTML=rows.map(x=>`<article class="app"><h3>${x.title}</h3><p>${x.desc}</p><dl><dt>Primary</dt><dd>${x.primary}</dd><dt>Fallback</dt><dd>${x.fallback}</dd><dt>自動化</dt><dd>${x.auto}</dd><dt>風險</dt><dd>${x.risk}</dd></dl></article>`).join('')}
function advisor(){const f=Object.fromEntries(new FormData($('#advisor')).entries());let primary='Gemini App + Notebook',fallback='免費版先驗證';if(f.account==='developer'||f.goal==='build'){primary='Google AI Studio + Gemini API';fallback='Gemini App 原型'}else if(f.data==='sensitive'||f.scale==='org'){primary='Workspace + Gemini Enterprise';fallback='去識別化 PoC'}else if(f.goal==='automation'){primary=f.account==='workspace'?'Workspace Studio':'Google AI Pro + Spark';fallback='Scheduled Actions／人工核准'}else if(f.goal==='research'){primary='Deep Research + Notebook';fallback='Gemini App + Drive'}else if(f.goal==='content'){primary='Notebook + Canvas + Slides';fallback='Gemini App'};const approval=f.automation==='agent'||f.data!=='public'?'對外寄送、刪除、分享與正式寫入保留人工核准。':'先以公開資料驗證成果品質。';$('#advisorResult').innerHTML=`<h3>${primary}</h3><div class="result-grid"><div class="result-item"><b>Fallback</b><span>${fallback}</span></div><div class="result-item"><b>治理要求</b><span>${approval}</span></div><div class="result-item"><b>驗收</b><span>正確率 ≥95%；未授權外洩與未核准動作為 0。</span></div><div class="result-item"><b>不採用風險</b><span>私人帳號直接承載公司資料，將造成權限、歸屬與稽核缺口。</span></div></div>`}
function renderLayers(){$('#layers').innerHTML=layers.map((x,i)=>`<details ${i===0?'open':''}><summary>${x[0]}</summary><p>${x[1]}</p></details>`).join('')}
function setView(v){state.view=v;$$('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+v));$$('.bottom [data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));window.scrollTo({top:0,behavior:'smooth'});save()}
function dragInit(){if(!state.editing)return;$$('.drag').forEach(h=>h.addEventListener('pointerdown',e=>{const card=h.closest('.module');card.classList.add('dragging');h.setPointerCapture?.(e.pointerId);const move=ev=>{const target=document.elementFromPoint(ev.clientX,ev.clientY)?.closest('.module');$$('.module').forEach(x=>x.classList.remove('drop'));if(target&&target!==card)target.classList.add('drop')};const up=ev=>{const target=document.elementFromPoint(ev.clientX,ev.clientY)?.closest('.module');if(target&&target!==card){const a=state.order.indexOf(card.dataset.id),b=state.order.indexOf(target.dataset.id);state.order.splice(a,1);state.order.splice(b,0,card.dataset.id);save()}h.removeEventListener('pointermove',move);h.removeEventListener('pointerup',up);renderDashboard()};h.addEventListener('pointermove',move);h.addEventListener('pointerup',up)}))}
function init(){save();$('#role').value=state.role;$('#goal').value=state.goal;$('#data').value=state.data;profile();renderPlans();renderApps();advisor();renderLayers();setView(state.view);$('#role').onchange=profile;$('#goal').onchange=profile;$('#data').onchange=profile;$('#arrangeBtn').onclick=smart;$('#editBtn').onclick=()=>{state.editing=true;$('#editBar').hidden=false;renderDashboard()};$('#doneBtn').onclick=()=>{state.editing=false;$('#editBar').hidden=true;save();renderDashboard()};$('#resetBtn').onclick=()=>{state.order=[...defaults];save();renderDashboard()};$('#dashboard').onclick=e=>{const b=e.target.closest('[data-move]');if(!b)return;const card=b.closest('.module'),i=state.order.indexOf(card.dataset.id),j=b.dataset.move==='up'?i-1:i+1;if(j<0||j>=state.order.length)return;[state.order[i],state.order[j]]=[state.order[j],state.order[i]];save();renderDashboard()};$$('.bottom [data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#planA').onchange=e=>{state.planA=e.target.value;if(state.planA===state.planB){state.planB=state.planA==='pro'?'plus':'pro';$('#planB').value=state.planB;toast('已自動調整方案 B')}save();compare()};$('#planB').onchange=e=>{state.planB=e.target.value;if(state.planA===state.planB){state.planA=state.planB==='plus'?'pro':'plus';$('#planA').value=state.planA;toast('已自動調整方案 A')}save();compare()};$('#swapBtn').onclick=()=>{[state.planA,state.planB]=[state.planB,state.planA];renderPlans();save()};$('#planSearch').oninput=e=>{state.query=e.target.value.slice(0,80);compare();save()};$('#planGroup').onchange=e=>{state.group=e.target.value;compare();save()};$('#compareResult').onclick=e=>{if(e.target.closest('[data-clear]')){state.query='';state.group='all';renderPlans();save()}};$('#appFilters').onclick=e=>{const b=e.target.closest('[data-app]');if(!b)return;state.app=b.dataset.app;renderApps();save()};$('#advisor').onchange=advisor;$('#advisor').onsubmit=e=>{e.preventDefault();advisor();$('#advisorResult').scrollIntoView({behavior:'smooth',block:'start'})};$('#fontBtn').onclick=()=>{state.font=state.font===1?1.1:state.font===1.1?1.2:1;save();toast(`字級 ${Math.round(state.font*100)}%`)};$('#shareBtn').onclick=async()=>{const payload=btoa(unescape(encodeURIComponent(JSON.stringify({view:state.view,role:state.role,goal:state.goal,data:state.data,planA:state.planA,planB:state.planB,app:state.app,font:state.font,order:state.order}))));const url=location.href.split('#')[0]+'#s='+payload;try{await navigator.clipboard.writeText(url);toast('分享連結已複製')}catch{location.hash='s='+payload;toast('分享狀態已寫入網址')}}}
init();
})();
